name: sekom_clenner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core platform/system tooling
  process_run: ^0.12.5
  path_provider: ^2.1.1
  path: ^1.9.0
  file_picker: ^8.0.0+1
  audioplayers: ^5.2.1
  window_manager: ^0.3.9
  win32: ^5.7.0
  win32_registry: ^1.1.3
  ffi: ^2.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

  # UX + visuals
  shimmer: ^3.0.0
  intl: ^0.19.0
  logger: ^2.0.2
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.4
  package_info_plus: ^5.0.1
  flutter_local_notifications: ^16.3.0
  glassmorphism: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  badges: ^3.1.2

  # State & monitoring
  get_it: ^7.6.7
  flutter_riverpod: ^2.5.1
  sentry_flutter: ^7.18.0
  dartz: ^0.10.1

  # Native/system integrations
  connectivity_plus: ^5.0.2
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0

  # Hardware & diagnostics
  camera: ^0.10.5+9
  camera_windows: ^0.2.1+9
  record: ^4.4.4
  permission_handler: ^11.3.0
  battery_plus: ^5.0.2
  network_info_plus: ^5.0.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
